# Generated by Django 3.2 on 2022-12-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20221207_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Student's Name")),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personals',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personals', to='booking.personal'),
        ),
    ]
