# Generated by Django 3.2 on 2022-12-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20221207_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='surname',
            field=models.CharField(default=1, max_length=30, verbose_name='Surname'),
            preserve_default=False,
        ),
    ]
