# Generated by Django 3.2 on 2022-12-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_personal_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personals', to='booking.personal'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name="Student's Name"),
        ),
    ]
