# Generated by Django 3.2 on 2022-12-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_personal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='email',
            field=models.EmailField(default=1, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
