# Generated by Django 3.2 on 2022-12-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_personal_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xxxxx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Username')),
                ('email', models.TextField(verbose_name='Email')),
                ('password', models.TextField(verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'xxxxx',
                'verbose_name_plural': 'xxxxx',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='admin',
            field=models.EmailField(default=False, max_length=254, verbose_name='Admin'),
        ),
    ]
