# Generated by Django 3.2 on 2022-12-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20221213_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
    ]
