# Generated by Django 3.2 on 2022-12-20 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0009_alter_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='personals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
