# Generated by Django 3.2 on 2022-12-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20221220_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpole',
            name='image',
            field=models.ImageField(default=2, upload_to='Field/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
