# Generated by Django 3.2 on 2022-08-20 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Blog name')),
                ('context', models.TextField(verbose_name='Context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='product_image/Груша.jpg', upload_to='blog/', verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'blogs',
                'ordering': ['id'],
            },
        ),
    ]
