# Generated by Django 3.2 on 2022-08-19 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя компании')),
            ],
            options={
                'verbose_name': 'Фирма|Бренд',
                'verbose_name_plural': 'Фирмы|Бренды',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя категории')),
                ('image', models.ImageField(upload_to='category_image/', verbose_name='ФОТО')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Городы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('cash', 'Нал'), ('card', 'Карта'), ('odengi', 'О денги')], max_length=40, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Под-Категории')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('image', models.ImageField(upload_to='subcategory_image/', verbose_name='ФОТО')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.category', verbose_name='Выбор Категории')),
            ],
            options={
                'verbose_name': 'Под-Категория',
                'verbose_name_plural': 'Под-Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя продукта')),
                ('slug', models.SlugField(default='product-', unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='product_image/', verbose_name='ФОТО')),
                ('cur', models.CharField(choices=[('SOM', 'Сом'), ('USD', 'Доллар'), ('EURO', 'Евро'), ('RUB', 'Рубль')], default='SOM', max_length=4, verbose_name='Волюта')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('article', models.IntegerField(null=True, unique=True, verbose_name='Артикл')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата изменение')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creater', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='shopping.subcategory', verbose_name='Под-категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коментария',
                'verbose_name_plural': 'Коментарии',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='city',
            field=models.ManyToManyField(to='shopping.City', verbose_name='Выбор Города'),
        ),
    ]
