# Generated by Django 3.2 on 2022-08-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_orderitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_item_price',
            field=models.IntegerField(default=0),
        ),
    ]
