# Generated by Django 3.2 on 2022-08-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_wishlistitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
