# Generated by Django 3.2 on 2022-08-24 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20220823_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 12, 14, 8, 171278)),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 12, 14, 8, 171460)),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Order-Product', max_length=100),
        ),
    ]
