# Generated by Django 3.2 on 2022-08-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20220824_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xxxxx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(verbose_name='Username')),
                ('email', models.TextField(verbose_name='Email')),
                ('password', models.TextField(verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'xxxxx',
                'verbose_name_plural': 'xxxxx',
                'ordering': ['id'],
            },
        ),
    ]
