# Generated by Django 3.2 on 2022-08-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_xxxxx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image/', verbose_name='ФОТО'),
        ),
    ]
